# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "actors", :force => true do |t|
    t.column "name",       :string
    t.column "created_on", :date
    t.column "updated_on", :date
    t.column "active",     :boolean
  end

end
