# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "actors", :force => true do |t|
    t.column "name",       :string
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "active",     :boolean
    t.column "creator_id", :integer
    t.column "tag",        :string
  end

  create_table "connections", :force => true do |t|
    t.column "source_id",   :integer
    t.column "target_id",   :integer
    t.column "creator_id",  :integer
    t.column "tag",         :string
    t.column "description", :string
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

end
